codecov:
  require_ci_to_pass: yes
  notify:
    after_n_builds: 2
    wait_for_ci: yes
coverage:
  status:
    project:
      default:
        target: auto
        threshold: 0.2%
        if_ci_failed: error
        only_pulls: false
    patch:
      default:
        target: 100%
        threshold: 0%
        if_ci_failed: error
        only_pulls: false
ignore:
  - "mock_hmrc"
