version: '3'

services:
  lite-hmrc-postgres:
    restart: 'always'
    container_name: "lite-hmrc-postgres"
    environment:
      - LITEHMRC_DB_USER=postgres
      - LITEHMRC_DB_PASSWORD=password
      - LITEHMRC_DB_SCHEMA=postgres
      - POSTGRES_PASSWORD=password
    build: './database'
    expose:
      - 5432
    ports:
      - 5432:5432

  lite-hmrc-intg:
    container_name: "lite-hmrc-intg"
    env_file:
      - .env
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - lite-hmrc-postgres
      - lite-hmrc-ditmail
      - lite-hmrc-spiremail
    expose:
      - 8000
    command: pipenv run ./manage.py runserver 0.0.0.0:8000

  lite-hmrc-ditmail:
    container_name: "lite-hmrc-ditmail"
    build: ./mailserver
    ports:
      - "25:25"
      - "587:587"
      - "995:995"
      - "80:80"
    volumes:
       - ./mailserver/maildata:/var/vmail
    environment:
      EMAIL_DOMAIN: example.com
      RELAY_ADDRESS: api:10025
      CERTBOT_EMAIL: test@test.com
      USE_LETSENCRYPT: "no"
      MAIL_USERNAME: username
      MAIL_PASSWORD: password

  lite-hmrc-spiremail:
    container_name: "lite-hmrc-spiremail"
    build: ./mailserver
    ports:
      - "26:25"
      - "588:587"
      - "996:995"
      - "81:80"
    volumes:
      - ./mailserver/maildata:/var/vmail
    environment:
      EMAIL_DOMAIN: spire.com
      RELAY_ADDRESS: api:10026
      CERTBOT_EMAIL: test@test.com
      USE_LETSENCRYPT: "no"
      MAIL_USERNAME: test
      MAIL_PASSWORD: password

volumes:
  maildata:
