version: "3.8"

services:
  lite-hmrc-postgres:
    restart: unless-stopped
    container_name: "lite-hmrc-postgres"
    environment:
      - LITEHMRC_DB_USER=postgres
      - LITEHMRC_DB_PASSWORD=password
      - LITEHMRC_DB_SCHEMA=postgres
      - POSTGRES_PASSWORD=password
    build: './database'
    expose:
      - 5432
    ports:
      - 5432:5432
    networks:
      - lite

  lite-hmrc-intg:
    container_name: "lite-hmrc-intg"
    env_file:
      - .env
    build: .
    platform: linux/amd64
    volumes:
      - .:/app
    ports:
      - 8000:8000
    depends_on:
      - lite-hmrc-postgres
    expose:
      - 8000
    command: pipenv run ./manage.py runserver 0.0.0.0:8000
    networks:
      - lite


  mailhog:
    ports:
      - 8025:8025  # HTTP
      - 587:1025  # SMTP
    image: mailhog/mailhog
    networks:
      - lite


  celery:
    build: .
    volumes:
      - .:/app
    env_file: .env
    links:
      - lite-hmrc-postgres
      - redis
    depends_on:
      - lite-hmrc-intg
    command: pipenv run watchmedo auto-restart -d . -R -p '*.py' -- celery -A conf worker -l info
    networks:
      - lite


  celery-scheduler:
    build: .
    volumes:
      - .:/app
    env_file: .env
    links:
      - lite-hmrc-postgres
      - redis
    depends_on:
      - lite-hmrc-intg
    command:  pipenv run watchmedo auto-restart -d . -R -p '*.py' -- celery -A conf beat
    networks:
      - lite


  redis:
    image: "redis:5-alpine"
    container_name: hmrc-redis
    expose:
      - 6379
    ports:
      - 6379:6379
    networks:
      - lite

networks:
  lite:
    external: true
volumes:
  maildata:
