# Generated by Django 4.2.16 on 2024-12-21 22:00

import uuid

import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [("mail", "0023_remove_mailreadstatus_mailbox_delete_mailboxconfig_and_more")]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name="MailboxConfig",
                    fields=[
                        (
                            "created",
                            model_utils.fields.AutoCreatedField(
                                default=django.utils.timezone.now, editable=False, verbose_name="created"
                            ),
                        ),
                        (
                            "modified",
                            model_utils.fields.AutoLastModifiedField(
                                default=django.utils.timezone.now, editable=False, verbose_name="modified"
                            ),
                        ),
                        (
                            "username",
                            models.TextField(
                                help_text="Username of the POP3 mailbox", primary_key=True, serialize=False
                            ),
                        ),
                    ],
                    options={
                        "db_table": "mail_mailboxconfig",
                    },
                ),
                migrations.CreateModel(
                    name="MailReadStatus",
                    fields=[
                        (
                            "created",
                            model_utils.fields.AutoCreatedField(
                                default=django.utils.timezone.now, editable=False, verbose_name="created"
                            ),
                        ),
                        (
                            "modified",
                            model_utils.fields.AutoLastModifiedField(
                                default=django.utils.timezone.now, editable=False, verbose_name="modified"
                            ),
                        ),
                        ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                        (
                            "message_num",
                            models.TextField(
                                default="",
                                help_text="Sequence number of the message as assigned by pop3 when the messages list is requested from the mailbox",
                            ),
                        ),
                        (
                            "message_id",
                            models.TextField(
                                default=uuid.uuid4,
                                help_text="Unique Message-ID of the message that is retrieved from the message header",
                                unique=True,
                            ),
                        ),
                        (
                            "status",
                            models.TextField(
                                choices=[("READ", "Read"), ("UNREAD", "Unread"), ("UNPROCESSABLE", "Unprocessable")],
                                db_index=True,
                                default="UNREAD",
                            ),
                        ),
                        (
                            "mailbox",
                            models.ForeignKey(
                                on_delete=django.db.models.deletion.CASCADE, to="mailboxes.mailboxconfig"
                            ),
                        ),
                    ],
                    options={
                        "db_table": "mail_mailreadstatus",
                    },
                ),
            ],
        ),
    ]
