# Generated by Django 4.2.16 on 2024-12-23 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailboxes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailreadstatus",
            name="mailbox",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mail_read_statuses",
                to="mailboxes.mailboxconfig",
            ),
        ),
    ]
