# Generated by Django 4.2.16 on 2024-12-23 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailboxes", "0002_alter_mailreadstatus_mailbox"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailreadstatus",
            name="mail_data",
            field=models.BinaryField(null=True),
        ),
    ]
