# Generated by Django 2.2.13 on 2020-07-10 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageupdate", name="has_spire_data", field=models.NullBooleanField(default=None),
        ),
    ]
