# Generated by Django 2.2.13 on 2020-07-16 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transactionmapping",
            name="line_number",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
