# Generated by Django 2.2.13 on 2020-07-14 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(model_name="licencepayload", name="old_lite_id", field=models.UUIDField(null=True),),
        migrations.AddField(
            model_name="licencepayload", name="old_reference", field=models.CharField(max_length=35, null=True),
        ),
    ]
