# Generated by Django 2.2.13 on 2020-06-22 08:39

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageupdate", name="lite_payload", field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name="usageupdate", name="lite_sent_at", field=models.DateTimeField(blank=True, null=True),
        ),
    ]
