# Generated by Django 2.2.13 on 2020-06-19 11:57

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageupdate", name="lite_payload", field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
