# Generated by Django 2.2.13 on 2020-07-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_auto_20200714_0927"),
    ]

    operations = [
        migrations.AlterModelOptions(name="licencepayload", options={"ordering": ["received_at"]},),
    ]
