# Generated by Django 2.2.13 on 2020-06-23 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0002_auto_20200622_0839"),
    ]

    operations = [
        migrations.AddField(
            model_name="usageupdate", name="has_lite_data", field=models.NullBooleanField(default=None),
        ),
    ]
