# Generated by Django 2.2.13 on 2020-07-13 13:38

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0003_auto_20200710_1438"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usageupdate", name="licence_ids", field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
