# Generated by Django 2.2.10 on 2020-06-10 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0009_licencepayload"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganisationIdMapping",
            fields=[
                ("lite_id", models.CharField(max_length=36, unique=True)),
                ("rpa_trader_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="GoodIdMapping",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("lite_id", models.CharField(max_length=36)),
                ("licence_reference", models.CharField(max_length=35)),
                ("line_number", models.PositiveIntegerField()),
            ],
            options={"unique_together": {("lite_id", "licence_reference")},},
        ),
    ]
