# Generated by Django 2.2.10 on 2020-06-10 10:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0009_licencepayload"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoodIdMapping",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("lite_id", models.CharField(max_length=36)),
                ("licence_reference", models.CharField(max_length=35)),
                ("line_number", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="OrganisationIdMapping",
            fields=[
                ("lite_id", models.CharField(max_length=36, unique=True)),
                ("rpa_trader_id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
