# Generated by Django 2.2.13 on 2020-06-12 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0010_goodidmapping_organisationidmapping"),
    ]

    operations = [
        migrations.RemoveField(model_name="mail", name="errors",),
        migrations.RemoveField(model_name="mail", name="serializer_errors",),
        migrations.AddField(model_name="mail", name="sent_data", field=models.TextField(blank=True, null=True),),
        migrations.AddField(model_name="mail", name="sent_filename", field=models.TextField(blank=True, null=True),),
    ]
