# Generated by Django 2.2.13 on 2020-06-12 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0011_auto_20200612_1359"),
    ]

    operations = [
        migrations.RenameField(model_name="licenceupdate", old_name="license_ids", new_name="licence_ids",),
    ]
