# Generated by Django 2.2.13 on 2020-06-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0012_auto_20200612_1401"),
    ]

    operations = [
        migrations.RenameField(model_name="usageupdate", old_name="license_ids", new_name="licence_ids",),
        migrations.AddField(
            model_name="mail", name="sent_response_data", field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="mail", name="sent_response_filename", field=models.TextField(blank=True, null=True),
        ),
    ]
