# Generated by Django 4.2.16 on 2024-12-21 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mail", "0022_alter_licencedata_licence_payloads"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.RemoveField(
                    model_name="mailreadstatus",
                    name="mailbox",
                ),
                migrations.DeleteModel(
                    name="MailboxConfig",
                ),
                migrations.DeleteModel(
                    name="MailReadStatus",
                ),
            ],
        ),
    ]
